export default {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  FETCH_REPORTS: "FETCH_REPORTS",
  SELECT_REPORT: "SELECT_REPORT",
  FETCH_STATIC: "FETCH_STATIC",
  DELETE_REPORT: "DELETE_REPORT",
  UPDATE_REPORT: "UPDATE_REPORT"
};
